---
###########################
###########################
## Platform.io Actions   ##
###########################
###########################
name: PlatformIO CI

#
# Documentation:
# https://docs.platformio.org/en/latest/integration/ci/github-actions.html
#

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@v1
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install platformio
      - name: Run PlatformIO
        run: platformio run
